name: artisan
version: 0.0.1
publish_to: https://onepub.dev/api/ksdbxpsdav/
description: A new Flutter project.
environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.1.2
  local_auth: ^2.1.6
  google_sign_in: ^6.1.4
  image_picker: ^0.8.9
  path: ^1.8.3
  http: ^1.0.0
  logger: ^1.4.0
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  go_router: ^8.0.5
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1

  flutter_test:
    sdk: flutter
flutter: null
